name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Crear credentials.json desde Secret
      - name: Crear credentials.json desde secret
        run: echo "$GOOGLE_CREDENTIALS" > credentials.json
        shell: bash
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Instalar dependencias del sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip python3-setuptools git zip unzip \
            openjdk-8-jdk libncurses5 libstdc++6 libffi-dev \
            libssl-dev automake autoconf libtool pkg-config \
            zlib1g-dev

      - name: Instalar Buildozer y Cython
        run: |
          pip3 install --upgrade pip
          pip3 install cython==0.29.33 buildozer

      # 🔹 Guardar Keystore desde Secret
      - name: Crear keystore.jks
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > keystore.jks

      # 🔹 Compilar APK en release y firmar
      - name: Compilar APK release
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          buildozer -v android release 2>&1 | tee build.log

      # 🔹 Subir APK firmado como artefacto
      - name: Subir APK firmado
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: bin/*-release.apk

      # 🔹 Subir log completo
      - name: Subir log de compilación
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
