name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # 🔹 Crear credentials.json desde tu Secret privado
      - name: Crear credentials.json desde secret
        run: echo "$GOOGLE_CREDENTIALS" > credentials.json
        shell: bash
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Instalar dependencias del sistema
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools git zip unzip openjdk-8-jdk

      - name: Instalar Buildozer y Cython
        run: |
          pip3 install --upgrade pip
          pip3 install cython==0.29.33
          pip3 install buildozer

      # 🔹 Aceptar automáticamente licencias del SDK
      - name: Aceptar licencias de Android SDK
        run: yes | sdkmanager --licenses
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk
          PATH: /usr/local/lib/android/sdk/cmdline-tools/latest/bin:/usr/local/lib/android/sdk/platform-tools:$PATH

      # 🔹 Compilar APK y guardar log
      - name: Compilar APK
        run: buildozer -v android debug 2>&1 | tee build.log

      # 🔹 Subir APK como artefacto descargable
      - name: Subir APK como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: bin/*.apk

      # 🔹 Subir log completo como artefacto
      - name: Subir log de compilación
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
